version: '3.5'
services:
    db:
        container_name: libstore-db
        restart: always
        image: postgres:9.6
        env_file: dev-env
        ports:
            - 5432:5432
        volumes:
            - libstore-pg-data:/var/lib/postgresql/data

    api:
        container_name: libstore-api
        restart: always
        build: .
        env_file: dev-env
        command: ["sh", "scripts/start.sh"]
        ports:
            - 4000:4000
        volumes:
            - .:/work-at-olist
        depends_on:
            - db

volumes:
    libstore-pg-data: {}
