# Generated by Django 3.0.2 on 2020-03-13 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0002_auto_20200313_0157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.TextField(default=''),
        ),
    ]
